export { default as CART } from './cart.svg';
export { default as LOGO } from './logo.svg';
export { default as ADD_TO_CART } from './addToCart.svg';
export { default as REMOVE_TO_CART } from './removeToCart.svg';
export { default as UP_ARROW } from './upArrow.svg';
export { default as DOWN_ARROW } from './downArrow.svg';
export { default as MINUS_BUTTON } from './minusButton.svg';
export { default as PLUS_BUTTON } from './plusButton.svg';
export { default as REMOVE_BUTTON } from './removeButton.svg';
