const FIRST_PAGE_SIZE = 20;
const SIZE_PER_PAGE = 4;

const FIRST_PAGE = 0;
const GAP_WITH_FIRST_PAGE = FIRST_PAGE_SIZE / SIZE_PER_PAGE;

const MOCK_LAST_PAGE = 24;
const MOCK_TOTAL_SIZE = 100;

export {
  FIRST_PAGE_SIZE,
  SIZE_PER_PAGE,
  FIRST_PAGE,
  GAP_WITH_FIRST_PAGE,
  MOCK_LAST_PAGE,
  MOCK_TOTAL_SIZE,
};
