export const SHOP_INFO = {
  SHOPPING_MALL_TITLE: 'SHOP',
  PRODUCT_SECTION_TITLE: '우테코 상품 목록',
  CART_MODAL_TITLE: '장바구니',
  TOTAL_PRICE_TEXT: '총 결제 금액',
  CART_MODAL_CLOSE_BUTTON_TEXT: '닫기',
  DELETE_BUTTON_TEXT: '삭제',
  ADD_BUTTON_TEXT: '담기',
  REMOVE_BUTTON_TEXT: '빼기',
  SOLD_OUT_TEXT: '품절',
};
